### ISSUE TITLE
list index out of range in get_num_days_span 

### ISSUE THREAD

**Issue by christian-maigaard** [scaubrey/InsuLearner#2]
Hi! 

I tried to run InsuLeaner and got the following stack trace. The culprit seems to be 

`data_end_date = list(timeline.items())[0][0]` 

I have data in Tidepool, so not sure what the issue might be 

```
2023-05-09 09:01:33,887 - InsuLearner.insulearner - DEBUG - Args:
2023-05-09 09:01:33,887 - InsuLearner.insulearner - DEBUG - estimation_window_size_days: 30
2023-05-09 09:01:33,887 - InsuLearner.insulearner - DEBUG - height_inches: 67.0
2023-05-09 09:01:33,888 - InsuLearner.insulearner - DEBUG - weight_lbs: 172.0
2023-05-09 09:01:33,888 - InsuLearner.insulearner - DEBUG - gender: male
2023-05-09 09:01:33,888 - InsuLearner.insulearner - DEBUG - CSF: None
2023-05-09 09:01:33,888 - InsuLearner.insulearner - DEBUG - estimate_agg_boundaries: True
2023-05-09 09:01:33,888 - InsuLearner.insulearner - DEBUG - agg_period_window_size_hours: 24
2023-05-09 09:01:33,888 - InsuLearner.insulearner - DEBUG - agg_period_hop_size_hours: 24
2023-05-09 09:01:33,888 - InsuLearner.insulearner - INFO - CSF estimated to be 4.67 for height_inches 67.0, weight_lbs 172.0, and gender male
2023-05-09 09:01:33,888 - InsuLearner.insulearner - INFO - Running for dates 2023-04-08 09:01:33.888149 to 2023-05-08 09:01:33.888149
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/insulearner", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/InsuLearner/insulearner.py", line 351, in main
    user_obj = load_user_data(tp_username, tp_password, data_start_date, data_end_date, estimation_window_size_days)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/InsuLearner/insulearner.py", line 275, in load_user_data
    total_basal_days = user.get_num_days_span(data_type="basal")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/InsuLearner/tidepool/tidepool_user_model.py", line 531, in get_num_days_span
    data_end_date = list(timeline.items())[0][0]
IndexError: list index out of range
```

**Comment by scaubrey** [comment]
Hi Christian, it looks like there are no basal events for some reason. Is there any basal data in that date range when you look at your Tidepool account on the web?

**Comment by christian-maigaard** [comment]
Ah! That might makes sense since I'm running Loop with micro-bolus enabled 🤔

**Comment by scaubrey** [comment]
I'm also running Loop with micro-bolus enabled for my son, but his basal schedule still sends basal events to Tidepool. What pump are you using? Does it have basal delivery active?

**Comment by christian-maigaard** [comment]
Hi! Everything looked fine to me in Tidepool. I.e I had some data. However when checked Loop, the Tidepool connection seemed to be broken. Re-did the integration to Tidepool, and that seems to have fixed the issue :) 

Thank you for the pointers, and the tool. I'm looking forward to explore it more 👍 . Ill close this issue
